import type { Metadata } from "next";
import "./globals.css";
import { store } from '../../@redux/index'
import { Provider } from 'react-redux'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <>this is a private layout</>
          {children}
        </body>
      </html>
    </Provider>
  );
}
