import type { Metadata } from "next";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Chat App By Kartik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors position="top-right" /> {/* position optional */}
      </body>
    </html>
  );
}
