import type { Metadata } from "next";
import { toast, Toaster } from 'sonner'
import { ChatBox, ChatArea } from "@/app/@components";

export const metadata: Metadata = {
  title: "Chat App By Kartik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-12">
          <div className="col-span-12 md:col-span-9">
            {children}
            <Toaster richColors position="top-right" />
          </div>
          <div className="hiden md:col-span-3">
            <ChatBox />
          </div>
        </div>
      </body>
    </html>
  );
}
